SELECT DISTINCT   
    RAS_HOUSEHOLD_UNIT.taxYear taxYear,    
    RAS_HOUSEHOLD_UNIT.propertyId propertyId,    
    RAS_PROPERTY_DESCRIPTION.zipCode zipCode,    
    RAS_PROPERTY_DESCRIPTION.state state,    
    RAS_PROPERTY_DESCRIPTION.city city,    
    RAS_PROPERTY_DESCRIPTION.address address    
FROM    
    (((RAS_HOUSEHOLD_UNIT JOIN RAS_REPORT_CATEGORY ON RAS_REPORT_CATEGORY.name = 'LANDLORD') JOIN RAS_REPORT ON RAS_REPORT_CATEGORY.categoryId = RAS_REPORT.categoryId AND RAS_REPORT.reportName = 'Landlord Missing Rental Properties') JOIN RAS_PROPERTY_DESCRIPTION ON RAS_HOUSEHOLD_UNIT.taxYear = RAS_PROPERTY_DESCRIPTION.taxYear AND RAS_HOUSEHOLD_UNIT.propertyId = RAS_PROPERTY_DESCRIPTION.propertyId) 
LEFT JOIN RAS_PROPERTY ON RAS_HOUSEHOLD_UNIT.taxYear = RAS_PROPERTY.taxYear AND RAS_HOUSEHOLD_UNIT.propertyId = RAS_PROPERTY.propertyId
