SELECT rm.STATE
, rm.COUNTY
--, rm.MUNICIPALITY
, COUNT(*) AS COUNT
FROM RAS.RAS_PROPERTY rp
JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rp.STATE AND rm.CODE = rp.MUNICIPALITY_CODE)
GROUP BY rm.STATE, rm.COUNTY --, rm.MUNICIPALITY
ORDER BY COUNT(*) DESC;

