SELECT rm.COUNTY AS COUNTY
, rm.MUNICIPALITY AS MUNICIPALITY
, rpd.PROPERTY_LOCATION
, rpd.OWNER_NAME
, rpd.OWNER_ADDRESS
, rpd.OWNER_CITY
, rpd.OWNER_STATE
FROM RAS.RAS_MUNICIPALITY rm
JOIN RAS.RAS_PROPERTY rp ON (rp.STATE = rm.STATE AND rp.MUNICIPALITY_CODE = rm.CODE)
JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = rp.PROPERTY_ID AND rpd.LOAD_TAX_YEAR = rp.TAX_YEAR)
WHERE rm.COUNTY LIKE 'Union County%'
--AND rm.code = '2012'
AND rm.code = '2005'
ORDER BY rm.COUNTY, rm.MUNICIPALITY;
