SELECT pinj.COUNTY_DISTRICT
, pinj.BLOCK
, pinj.LOT
, pinj.PROPERTY_LOCATION
, pinj.DEED_BOOK
, pinj.DEED_PAGE
, pinj.OWNER_NAME
, pinj.PROPERTY_CLASS
, pinj.TAX_ACCOUNT_NUMBER
, COUNT(*) AS PROPERTY_COUNT
FROM RAS_STG.PROPERTY_INFO_NJ pinj
JOIN RAS_STG.MUNICIPALITY_NJ mun ON (mun.CODE = pinj.COUNTY_DISTRICT)
WHERE mun.MUNICIPALITY = 'NORTH BERGEN TWP'
GROUP BY pinj.COUNTY_DISTRICT, pinj.BLOCK, pinj.LOT, pinj.PROPERTY_LOCATION, pinj.DEED_BOOK, pinj.DEED_PAGE, pinj.OWNER_NAME, pinj.PROPERTY_CLASS, pinj.tax_account_number
HAVING COUNT(*) >= 2
ORDER BY COUNT(*) DESC;
