SELECT ras_stg.RAS_STG_CITY
, ras_stg.RAS_STG_COUNT
, ras.RAS_COUNT
, (ras_stg.RAS_STG_COUNT - ras.RAS_COUNT) AS DIFFERENCE
FROM (
    SELECT mun.MUNICIPALITY AS RAS_STG_CITY
    , COUNT(*) AS RAS_STG_COUNT
    FROM RAS_STG.PROPERTY_INFO_NJ pinj
    JOIN RAS_STG.MUNICIPALITY_NJ mun ON (mun.CODE = pinj.COUNTY_DISTRICT)
    GROUP BY mun.MUNICIPALITY
    --ORDER BY COUNT(*) DESC
) ras_stg
JOIN (
    SELECT PROPERTY_CITY AS RAS_CITY
    , COUNT(*) AS RAS_COUNT
    FROM RAS.RAS_PROPERTY_DESCRIPTION
    GROUP BY PROPERTY_CITY
) ras ON (ras.RAS_CITY = ras_stg.RAS_STG_CITY)
WHERE RAS_STG_COUNT != RAS_COUNT
ORDER BY DIFFERENCE DESC;
