DROP VIEW RPT_PROPERTY_WITHOUT_LANDLORD_VW;

CREATE VIEW RPT_PROPERTY_WITHOUT_LANDLORD_VW
AS
    SELECT prop.TAX_YEAR
    , rm.STATE 
    , rm.COUNTY
    , rm.MUNICIPALITY
    , prop.PROPERTY_ID
    , rpt.PROPERTY_DESCRIPTION
    , rpd.PROPERTY_CITY
    , rpd.PROPERTY_LOCATION
    , rpd.NUMBER_OF_APARTMENTS
    , rpd.BLOCK
    , rpd.LOT
    , rpd.CENSUS_TRACT
    , rpd.CENSUS_BLOCK
    , rpd.DEED_BOOK
    , rpd.DEED_PAGE
    , rpd.DEED_DATE
    , rpd.OWNER_NAME
    , rpd.OWNER_CITY
    , rpd.OWNER_STATE
    , rpd.OWNER_ADDRESS
    , rpd.OWNER_ZIPCODE
    FROM (
        SELECT rhu.TAX_YEAR
        , rhu.PROPERTY_ID
        FROM RAS.RAS_HOUSEHOLD_UNIT rhu
        LEFT JOIN RAS.RAS_PROPERTY rp ON (rp.TAX_YEAR = rhu.TAX_YEAR AND rp.PROPERTY_ID = rhu.PROPERTY_ID)
        WHERE rp.LANDLORD_TAX_ID IS NULL
    ) prop
    JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = prop.PROPERTY_ID)
    JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpd.STATE AND rm.CODE = rpd.MUNICIPALITY_CODE)
    JOIN RAS.RAS_PROPERTY_TYPE rpt ON (rpt.PROPERTY_TYPE = rpd.PROPERTY_TYPE);
