DROP VIEW RPT_RENTAL_INCOME_DIFFERENCE_VW;

CREATE VIEW RPT_RENTAL_INCOME_DIFFERENCE_VW
AS
    SELECT ll.TAX_YEAR
    , ll.PROPERTY_ID
    , ll.PERCENTAGE_OWNED
    , ll.LANDLORD_COUNT
    , ll.LL_RENTAL_INCOME
    , tnt.TENANT_PAYMENTS
    , (ll.LL_RENTAL_INCOME - tnt.TENANT_PAYMENTS) AS NET_REPORTED_DIFFERENCE
    , rpt.PROPERTY_DESCRIPTION
    , rm.STATE 
    , rm.COUNTY
    , rm.MUNICIPALITY
    , rpd.PROPERTY_LOCATION
    , rpd.BLOCK
    , rpd.LOT
    , rpd.CENSUS_TRACT
    , rpd.CENSUS_BLOCK
    , rpd.DEED_BOOK
    , rpd.DEED_PAGE
    , rpd.DEED_DATE
    FROM (
        SELECT rp.TAX_YEAR
        , rp.PROPERTY_ID
        , SUM(rp.PERCENTAGE_OWNED) AS PERCENTAGE_OWNED
        , COUNT(*) AS LANDLORD_COUNT
        , SUM(rp.RENTAL_INCOME_RECEIVED) AS LL_RENTAL_INCOME
        FROM RAS.RAS_PROPERTY rp
        GROUP BY rp.TAX_YEAR, rp.PROPERTY_ID
    ) ll
    JOIN (
        SELECT rtph.TAX_YEAR
        , rtph.PROPERTY_ID
        , SUM(rtph.TOTAL_PAYMENTS) AS TENANT_PAYMENTS
        , COUNT(*) AS TENANT_COUNT
        FROM RAS.RAS_TENANT_PAYMENT_HISTORY rtph
        GROUP BY rtph.TAX_YEAR, rtph.PROPERTY_ID
    ) tnt ON (tnt.TAX_YEAR = ll.TAX_YEAR AND tnt.PROPERTY_ID = ll.PROPERTY_ID)
    JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = ll.PROPERTY_ID)
    JOIN RAS.RAS_PROPERTY_TYPE rpt ON (rpt.PROPERTY_TYPE = rpd.PROPERTY_TYPE)
    JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpd.STATE AND rm.CODE = rpd.MUNICIPALITY_CODE)
    WHERE ll.LL_RENTAL_INCOME != tnt.TENANT_PAYMENTS
;

