DROP VIEW RPT_PROPERTY_OWNERSHIP_NOT_100_PCT_VW;

CREATE VIEW RPT_PROPERTY_OWNERSHIP_NOT_100_PCT_VW
AS
    SELECT prop.TAX_YEAR
    , rm.STATE 
    , rm.COUNTY
    , rm.MUNICIPALITY
    , prop.PROPERTY_ID
    , prop.PERCENTAGE_OWNED
    , rpt.PROPERTY_DESCRIPTION
    , rpd.PROPERTY_COUNTRY
    , rpd.PROPERTY_CITY
    , rpd.PROPERTY_LOCATION
    , rpd.BLOCK
    , rpd.LOT
    , rpd.CENSUS_TRACT
    , rpd.CENSUS_BLOCK
    , rpd.YEAR_CONSTRUCTED
    , rpd.DEED_BOOK
    , rpd.DEED_DATE
    , rpd.OWNER_NAME
    , rpd.OWNER_CITY
    , rpd.OWNER_STATE
    , rpd.OWNER_ADDRESS
    , rpd.OWNER_ZIPCODE
    , rpd.OWNER_COUNTRY
    FROM (
        SELECT rp.TAX_YEAR
        , rp.PROPERTY_ID
        , SUM(rp.PERCENTAGE_OWNED) AS PERCENTAGE_OWNED
        FROM RAS.RAS_PROPERTY rp
        GROUP BY rp.TAX_YEAR, rp.PROPERTY_ID
        HAVING SUM(rp.PERCENTAGE_OWNED) != 100
    ) prop
    JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = prop.PROPERTY_ID)
    JOIN RAS.RAS_PROPERTY_TYPE rpt ON (rpt.PROPERTY_TYPE = rpd.PROPERTY_TYPE)
    JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpd.STATE AND rm.CODE = rpd.MUNICIPALITY_CODE);
