SELECT DISTINCT rpby.TAX_YEAR
, rpby.STATE
, rm.COUNTY
, rm.MUNICIPALITY
, rpd.PROPERTY_LOCATION
FROM RAS.RAS_PROPERTY_BASE_YEAR rpby
JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpby.STATE AND rm.CODE = rpby.CODE)
JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpby.TAX_YEAR = rpd.TAX_YEAR AND rpd.PROPERTY_ID = rpby.PROPERTY_ID)
WHERE rm.COUNTY LIKE 'UNION COUNTY%'
AND rpd.OWNER_NAME LIKE 'MILLER%CHEV%'
ORDER BY rpby.TAX_YEAR, rpby.STATE, rm.COUNTY, rm.MUNICIPALITY;
