DROP VIEW RAS_STATE_COUNTY_VW;

CREATE VIEW RAS_STATE_COUNTY_VW
AS
    SELECT STATE
    , COUNTY
    FROM RAS.RAS_MUNICIPALITY
    GROUP BY STATE, COUNTY;

ALTER VIEW RAS_STATE_COUNTY_VW 
ADD CONSTRAINT STATE_COUNTY_PK 
PRIMARY KEY (STATE, COUNTY) DISABLE NOVALIDATE;

--ALTER VIEW RAS_STATE_COUNTY_VW
--ADD CONSTRAINT RAS_STATE_COUNTY_VW_FK FOREIGN KEY (STATE,COUNTY) 
--REFERENCES RAS.RAS_MUNICIPALITY(STATE, COUNTY) DISABLE NOVALIDATE;

--CREATE UNIQUE INDEX RAS_STATE_COUNTY_IDX ON RAS.RAS_MUNICIPALITY(STATE,COUNTY,CODE);
