SELECT st.STATE_CODE
, stcnty.COUNTY
, mun.MUNICIPALITY
, COUNT(*) AS COUNT
FROM RAS.RAS_STATE st
JOIN RAS.RAS_STATE_COUNTY stcnty ON (stcnty.STATE_CODE = st.STATE_CODE)
JOIN RAS.RAS_MUNICIPALITY mun ON (mun.STATE = stcnty.STATE_CODE AND mun.COUNTY = stcnty.COUNTY)
JOIN RAS.RAS_PROPERTY prop ON (prop.STATE = mun.STATE AND prop.MUNICIPALITY_CODE = mun.CODE)
GROUP  BY st.STATE_CODE, stcnty.COUNTY, mun.MUNICIPALITY
