CREATE TABLE RAS_CITY.LANDLORD(
LANDLORD_ID int
, FIRST_NAME VARCHAR(100)
, LAST_NAME VARCHAR(100)
, TELEPHONE_MAIN VARCHAR(20)
, TELEPHONE_SECONDARY VARCHAR(20)
, STREET VARCHAR(100)
, CITY VARCHAR(100)
);
