CREATE TABLE RAS_CITY.USER_REPORTING(
USER_ID int
, USER_NAME VARCHAR(50)
, EMAIL VARCHAR(50) NULL
, TELEPHONE VARCHAR(20) NULL
, CITY VARCHAR(50) NULL
, STATE CHAR(2) NULL
, COUNTRY VARCHAR(50) NULL
);

