DROP VIEW RAS.LANDLORDS_BY_CITY;

CREATE VIEW RAS.LANDLORDS_BY_CITY
AS
    SELECT rl.TAX_YEAR
    , rl.TAXID
    , rl.FIRST_NAME
    , rl.MIDDLE_NAME
    , rl.LAST_NAME
    , rl.GROSS_INCOME
    , rl.ADDRESS
    , rl.CITY
    , rl.STATE
    , rl.ZIP_CODE
    , rl.COUNTRY
    , count(*) AS RENTAL_PROPERTY_COUNT
    FROM RAS.RAS_LANDLORD rl
    JOIN RAS.RAS_PROPERTY rp ON (rp.TAX_YEAR = rl.TAX_YEAR AND rp.LANDLORD_TAX_ID = rl.TAXID)
    GROUP BY rl.TAX_YEAR, rl.TAXID, rl.FIRST_NAME, rl.MIDDLE_NAME, rl.LAST_NAME, rl.GROSS_INCOME, rl.ADDRESS, rl.CITY, rl.STATE, rl.ZIP_CODE, rl.COUNTRY
