DROP VIEW RAS.LANDLORD_PROPERTIES_BY_CITY;

CREATE VIEW RAS.LANDLORD_PROPERTIES_BY_CITY
AS
    SELECT rm.STATE
    , rm.COUNTY
    , rm.MUNICIPALITY
    , rp.TAX_YEAR
    , rl.FIRST_NAME
    , rl.LAST_NAME
    , rl.TAXID
    , rl.ADDRESS AS LANDLORD_ADDRESS
    , rl.CITY AS LANDLORD_CITY
    , rl.STATE AS LANDLORD_STATE
    , rav.VIOLATION_POINTS AS AUDIT_VIOLATIONS
    , rpd.PROPERTY_LOCATION
    , rpd.PROPERTY_CITY
    , rpd.STATE AS PROPERTY_STATE
    , rpd.PROPERTY_ID
    , rp.RENTAL_INCOME_RECEIVED
    FROM RAS.RAS_MUNICIPALITY rm
    JOIN RAS.RAS_PROPERTY rp ON (rp.STATE = rm.STATE AND rp.MUNICIPALITY_CODE = rm.CODE)
    JOIN RAS.RAS_LANDLORD rl ON (rl.TAXID = rp.LANDLORD_TAX_ID AND rl.TAX_YEAR = rp.TAX_YEAR)
    JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = rp.PROPERTY_ID)
    JOIN (
        SELECT rav.TAX_YEAR
        , rav.PROPERTY_ID
        , SUM(ra.VIOLATION_POINTS) AS VIOLATION_POINTS
        FROM RAS.RAS_AUDIT_VIOLATION rav
        JOIN RAS.RAS_AUDIT ra ON (ra.AUDIT_ID = rav.AUDIT_ID)
        GROUP BY rav.TAX_YEAR, rav.PROPERTY_ID
    ) rav ON (rav.TAX_YEAR = rp.TAX_YEAR AND rav.PROPERTY_ID = rp.PROPERTY_ID)
;
    
