DROP VIEW RAS_AUDIT_VIOLATIONS_BY_CITY;

CREATE VIEW RAS_AUDIT_VIOLATIONS_BY_CITY
AS
    SELECT rsc.STATE_CODE AS STATE
    , rsc.COUNTY
    , rm.MUNICIPALITY
    , ra.AUDIT_NAME
    , count(*) AS AUDIT_COUNT
    FROM RAS.RAS_PROPERTY rp
    JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rp.STATE AND rm.CODE = rp.MUNICIPALITY_CODE)
    JOIN RAS.RAS_STATE_COUNTY rsc ON (rsc.STATE_CODE = rm.STATE AND rsc.COUNTY = rm.COUNTY)
    JOIN RAS.RAS_AUDIT_VIOLATION rav ON (rav.TAX_YEAR = rp.TAX_YEAR AND rav.PROPERTY_ID = rp.PROPERTY_ID)
    JOIN RAS.RAS_AUDIT ra ON (ra.AUDIT_ID = rav.AUDIT_ID)
    GROUP BY rsc.STATE_CODE, rsc.COUNTY, rm.MUNICIPALITY, ra.AUDIT_NAME;
