DROP VIEW RAS.RENTAL_PROPERTY_INFO_VW;

CREATE VIEW RAS.RENTAL_PROPERTY_INFO_VW
AS
    SELECT rpby.TAX_YEAR
    , rpby.STATE
    , rm.COUNTY
    , rm.MUNICIPALITY
    , rpby.PROPERTY_ID
    , rpt.PROPERTY_DESCRIPTION
    , rp.LANDLORD_TAX_ID
    , rp.PERCENTAGE_OWNED
    , rp.RENTAL_INCOME_RECEIVED
    , rp.TOTAL_DEDUCTIONS
    , rp.PROPERTY_TAXES
    , rpd.PROPERTY_LOCATION
    , rpd.TAX_ACCOUNT_NUMBER
    , rpd.BLOCK
    , rpd.LOT
    , rpd.CENSUS_TRACT
    , rpd.CENSUS_BLOCK
    , rpd.YEAR_CONSTRUCTED
    , rpd.DEED_BOOK
    , rpd.DEED_PAGE
    , rpd.DEED_DATE
    , rpd.OWNER_NAME
    , rpd.OWNER_CITY
    , rpd.OWNER_STATE
    , rpd.OWNER_ADDRESS
    , rpd.OWNER_ZIPCODE
    , rpd.OWNER_COUNTRY
    FROM RAS.RAS_PROPERTY_BASE_YEAR rpby
    JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpby.STATE AND rm.CODE = rpby.CODE)
    JOIN RAS.RAS_PROPERTY rp ON (rp.TAX_YEAR = rpby.TAX_YEAR AND rp.STATE = rpby.STATE AND rp.PROPERTY_ID = rpby.PROPERTY_ID)
    JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = rp.PROPERTY_ID)
    JOIN RAS.RAS_PROPERTY_TYPE rpt ON (rpt.PROPERTY_TYPE = rpd.PROPERTY_TYPE);
