DROP VIEW RAS.SUMMARIZE_RENTAL_PROPERTIES_BY_COUNTY;

CREATE VIEW RAS.SUMMARIZE_RENTAL_PROPERTIES_BY_COUNTY
AS
    SELECT ll.STATE 
    , ll.COUNTY
    , ll.TAX_YEAR
    , ll.PROPERTY_COUNT
    , ll.RENTAL_INCOME_RECEIVED AS RENTAL_INCOME_RECEIVED
    , tnt.HOUSEHOLD_COUNT AS HOUSEHOLD_COUNT
    , tnt.TOTAL_RENTAL_PAYMENTS AS TOTAL_RENTAL_PAYMENTS
    , ll.RENTAL_INCOME_RECEIVED - tnt.TOTAL_RENTAL_PAYMENTS AS "RENTAL_INCOME_DIFFERENCE"
    , ll.NUMBER_OF_PROPERTY_OWNERS
    , ll.TOTAL_DEDUCTIONS
    , ll.PROPERTY_TAXES
    , CAST(TRIM(CONCAT(CONCAT(ll.STATE,'_'), REPLACE(UPPER(ll.COUNTY), ' COUNTY', ''))) AS VARCHAR(50)) AS MAP_COUNTY
    FROM (
        SELECT srpbc.STATE 
        , srpbc.COUNTY
        , srpbc.TAX_YEAR
        , SUM(srpbc.PROPERTY_COUNT) AS PROPERTY_COUNT
        , SUM(srpbc.RENTAL_INCOME_RECEIVED) AS RENTAL_INCOME_RECEIVED
        , SUM(srpbc.NUMBER_OF_PROPERTY_OWNERS) AS NUMBER_OF_PROPERTY_OWNERS
        , SUM(srpbc.TOTAL_DEDUCTIONS) AS TOTAL_DEDUCTIONS
        , SUM(srpbc.PROPERTY_TAXES) AS PROPERTY_TAXES
        FROM RAS.SUMMARIZE_RENTAL_PROPERTIES_BY_CITY srpbc
        GROUP BY srpbc.STATE, srpbc.COUNTY, srpbc.TAX_YEAR
    ) ll
    JOIN (
        SELECT stbc.STATE
        , stbc.COUNTY
        , stbc.TAX_YEAR
        , sum(stbc.HOUSEHOLD_COUNT) AS HOUSEHOLD_COUNT
        , sum(stbc.TOTAL_RENTAL_PAYMENTS) AS TOTAL_RENTAL_PAYMENTS
        FROM SUMMARIZE_TENANTS_BY_CITY stbc
        GROUP BY stbc.STATE, stbc.COUNTY, stbc.TAX_YEAR
    ) tnt ON (tnt.STATE = ll.STATE AND tnt.COUNTY = ll.COUNTY AND tnt.TAX_YEAR = ll.TAX_YEAR);
