DROP VIEW RAS.SUMMARIZE_TENANTS_BY_CITY;

CREATE VIEW RAS.SUMMARIZE_TENANTS_BY_CITY
AS
    SELECT tnt.STATE
    , tnt.COUNTY
    , tnt.MUNICIPALITY
    , tnt.TAX_YEAR
    , tnt.HOUSEHOLD_COUNT
    , tnt.GROSS_INCOME
    , tnt.TOTAL_RENTAL_PAYMENTS
    , rp.RENTAL_INCOME_RECEIVED
    , (rp.RENTAL_INCOME_RECEIVED - tnt.TOTAL_RENTAL_PAYMENTS) AS RENTAL_INCOME_DIFFERENCE
    FROM (
        SELECT pwtv.STATE
        , pwtv.COUNTY
        , pwtv.MUNICIPALITY
        , pwtv.TAX_YEAR
        , count(*) AS HOUSEHOLD_COUNT
        , SUM(pwtv.GROSS_INCOME) AS GROSS_INCOME
        , SUM(pwtv.TOTAL_RENTAL_PAYMENTS) AS TOTAL_RENTAL_PAYMENTS
        FROM RAS.PROPERTIES_WITH_TENANTS_VW pwtv
        GROUP BY pwtv.STATE, pwtv.COUNTY, pwtv.MUNICIPALITY, pwtv.TAX_YEAR
    ) tnt
    JOIN (
        SELECT srpbc.STATE 
        , srpbc.COUNTY
        , srpbc.MUNICIPALITY
        , srpbc.TAX_YEAR
        , srpbc.RENTAL_INCOME_RECEIVED
        , srpbc.TOTAL_DEDUCTIONS
        , srpbc.PROPERTY_TAXES
        , srpbc.PROPERTY_COUNT
        FROM RAS.SUMMARIZE_RENTAL_PROPERTIES_BY_CITY srpbc
    ) rp ON (rp.STATE = tnt.STATE AND rp.COUNTY = tnt.COUNTY AND rp.MUNICIPALITY = tnt.MUNICIPALITY AND rp.TAX_YEAR = tnt.TAX_YEAR)
;
