DROP VIEW RAS.SUMMARIZE_LANDLORDS_BY_STATE_VW;

CREATE VIEW RAS.SUMMARIZE_LANDLORDS_BY_STATE_VW
AS
    SELECT srpbc.STATE
    , srpbc.TAX_YEAR
    , SUM(srpbc.PROPERTY_COUNT) AS LANDLORD_COUNT
    , SUM(srpbc.HOUSEHOLD_COUNT) AS HOUSEHOLD_COUNT
    , SUM(srpbc.RENTAL_INCOME_RECEIVED) AS RENTAL_INCOME_RECEIVED
    , SUM(srpbc.TOTAL_RENTAL_PAYMENTS) AS TOTAL_RENTAL_PAYMENTS
    , SUM(srpbc.RENTAL_INCOME_DIFFERENCE) AS RENTAL_INCOME_DIFFERENCE
    , SUM(srpbc.TOTAL_DEDUCTIONS) AS TOTAL_DEDUCTIONS
    , SUM(srpbc.PROPERTY_TAXES) AS PROPERTY_TAXES
    FROM RAS.SUMMARIZE_RENTAL_PROPERTIES_BY_COUNTY srpbc
    GROUP BY srpbc.STATE, srpbc.TAX_YEAR;
