DROP VIEW RAS.SUMMARIZE_PROPERTIES_WITH_TENANTS_BY_PROPERTY_VW;

CREATE VIEW RAS.SUMMARIZE_PROPERTIES_WITH_TENANTS_BY_PROPERTY_VW
AS
    SELECT psum.STATE
    , psum.COUNTY
    , psum.MUNICIPALITY
    , psum.TAX_YEAR
    , psum.TENANT_GROSS_INCOME
    , psum.TOTAL_TENANT_RENTAL_PAYMENTS
    , psum.PROPERTY_ID
    , rpt.PROPERTY_DESCRIPTION
    , rpd.PROPERTY_LOCATION
    , rpd.PROPERTY_CITY
    , rpd.PROPERTY_COUNTRY
    FROM (
        SELECT pwtvw."STATE"
        , pwtvw.COUNTY
        , pwtvw.MUNICIPALITY
        , pwtvw.TAX_YEAR
        , pwtvw.PROPERTY_ID
        , SUM(pwtvw.GROSS_INCOME) AS TENANT_GROSS_INCOME
        , SUM(pwtvw.TOTAL_RENTAL_PAYMENTS) AS TOTAL_TENANT_RENTAL_PAYMENTS
        FROM RAS.PROPERTIES_WITH_TENANTS_VW pwtvw
        GROUP BY pwtvw."STATE", pwtvw.COUNTY, pwtvw.MUNICIPALITY, pwtvw.TAX_YEAR, pwtvw.PROPERTY_ID
    ) psum
    JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = psum.PROPERTY_ID)
    JOIN RAS.RAS_PROPERTY_TYPE rpt ON (rpt.PROPERTY_CLASS = rpd.PROPERTY_CLASS);
