DROP VIEW RAS.SUMMARIZE_LANDLORDS_BY_PROPERTY_VW;

CREATE VIEW RAS.SUMMARIZE_LANDLORDS_BY_PROPERTY_VW
AS
    SELECT rm.STATE
    , rm.COUNTY
    , rm.MUNICIPALITY
    , rp.TAX_YEAR
    , rp.PROPERTY_ID
    , rl.FIRST_NAME
    , rl.MIDDLE_NAME
    , rl.LAST_NAME
    , rl.ADDRESS AS LANDLORD_ADDRESS
    , rl.CITY AS LANDLORD_CITY
    , rl.STATE AS LANDLORD_STATE
    , rl.ZIP_CODE AS LANDLORD_ZIPCODE
    , rl.COUNTRY AS LANDLORD_COUNTRY
    , rp.LANDLORD_TAX_ID
    , rp.PERCENTAGE_OWNED
    , rp.RENTAL_INCOME_RECEIVED
    , rp.NUMBER_OF_PROPERTY_OWNERS
    , rp.TOTAL_DEDUCTIONS
    , rp.PROPERTY_TAXES
    FROM RAS.RAS_PROPERTY_BASE_YEAR rpby
    JOIN RAS.RAS_PROPERTY rp ON (rp.TAX_YEAR = rpby.TAX_YEAR AND rp.PROPERTY_ID = rpby.PROPERTY_ID AND rp.STATE = rpby.STATE)
    JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpby.STATE AND rm.CODE = rpby.CODE)
    JOIN RAS.RAS_LANDLORD rl ON (rl.TAX_YEAR = rp.TAX_YEAR AND rl.TAXID = rp.LANDLORD_TAX_ID)
