DROP VIEW RAS.SUMMARIZE_LANDLORD_INFO_BY_CITY_VW;

CREATE VIEW RAS.SUMMARIZE_LANDLORD_INFO_BY_CITY_VW
AS
    SELECT cityll.TAX_YEAR AS PROPERTY_TAX_YEAR
    , rm.STATE AS PROPERTY_STATE
    , rm.COUNTY AS PROPERTY_COUNTY
    , rm.MUNICIPALITY AS PROPERTY_MUNICIPALITY
    , llp.FIRST_NAME
    , llp.MIDDLE_NAME
    , llp.LAST_NAME
    , llp.LANDLORD_TAX_ID
    , llp.ADDRESS AS LANDLORD_ADDRESS
    , llp.CITY AS LANDLORD_CITY
    , llp.STATE AS LANDLORD_STATE
    , llp.ZIP_CODE AS LANDLORD_ZIP_CODE
    , llp.COUNTRY AS LANDLORD_COUNTRY
    , llp.PROPERTY_COUNT
    , llp.RENTAL_INCOME_RECEIVED
    , llp.TOTAL_RENTAL_PAYMENTS
    , llp.RENTAL_INCOME_DIFFERENCE
    , llp.TOTAL_DEDUCTIONS
    , llp.PROPERTY_TAXES
    FROM (
        SELECT rp.TAX_YEAR
        , rp.STATE
        , rp.MUNICIPALITY_CODE
        , rp.LANDLORD_TAX_ID
        FROM RAS.RAS_PROPERTY rp
        GROUP BY rp.TAX_YEAR, rp.STATE, rp.MUNICIPALITY_CODE, rp.LANDLORD_TAX_ID
    ) cityll
    JOIN RAS.LANDLORD_PROFILE_VW llp ON (llp.TAX_YEAR = cityll.TAX_YEAR AND llp.LANDLORD_TAX_ID = cityll.LANDLORD_TAX_ID)
    JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = cityll.STATE AND rm.CODE = cityll.MUNICIPALITY_CODE)
