DROP VIEW RAS.SUMMARIZE_LANDLORDS_BY_COUNTY_VW;

CREATE VIEW RAS.SUMMARIZE_LANDLORDS_BY_COUNTY_VW
AS
    SELECT srpbc.STATE
    , srpbc.COUNTY
    , srpbc.TAX_YEAR
    , srpbc.PROPERTY_COUNT AS LANDLORD_COUNT
    , srpbc.HOUSEHOLD_COUNT
    , srpbc.RENTAL_INCOME_RECEIVED
    , srpbc.TOTAL_RENTAL_PAYMENTS
    , srpbc.RENTAL_INCOME_DIFFERENCE
    , srpbc.TOTAL_DEDUCTIONS
    , srpbc.PROPERTY_TAXES
    FROM RAS.SUMMARIZE_RENTAL_PROPERTIES_BY_COUNTY srpbc;

