DROP VIEW RAS.SUMMARIZE_RENTAL_PROPERTY_VW;

CREATE VIEW RAS.SUMMARIZE_RENTAL_PROPERTY_VW
AS
    SELECT rp.TAX_YEAR
    , rp.STATE 
    , rp.COUNTY
    , rp.MUNICIPALITY
    , rp.PROPERTY_ID
    , rp.LANDLORD_COUNT
    , rp.PERCENTAGE_OWNED
    , rp.RENTAL_INCOME_RECEIVED
    , tnt.TOTAL_RENTAL_PAYMENTS
    , rp.RENTAL_INCOME_RECEIVED - tnt.TOTAL_RENTAL_PAYMENTS AS RENTAL_INCOME_DIFFERENCE
    , rp.NUMBER_OF_PROPERTY_OWNERS
    , rp.TOTAL_DEDUCTIONS
    , rp.PROPERTY_TAXES
    FROM (
        SELECT rpby.TAX_YEAR
        , rpby.STATE
        , rm.COUNTY
        , rm.MUNICIPALITY
        , rpby.PROPERTY_ID
        , COUNT(*) AS LANDLORD_COUNT
        , SUM(rp.PERCENTAGE_OWNED) AS PERCENTAGE_OWNED
        , SUM(rp.RENTAL_INCOME_RECEIVED) AS RENTAL_INCOME_RECEIVED
        , SUM(rp.NUMBER_OF_PROPERTY_OWNERS) AS NUMBER_OF_PROPERTY_OWNERS
        , sum(rp.TOTAL_DEDUCTIONS) AS TOTAL_DEDUCTIONS
        , sum(rp.PROPERTY_TAXES) AS PROPERTY_TAXES
        FROM RAS.RAS_PROPERTY_BASE_YEAR rpby
        JOIN RAS.RAS_PROPERTY rp ON (rp.TAX_YEAR = rpby.TAX_YEAR AND rp.STATE = rpby.STATE AND rp.MUNICIPALITY_CODE = rpby.CODE AND rp.PROPERTY_ID = rpby.PROPERTY_ID)
        JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rp.STATE AND rm.CODE = rp.MUNICIPALITY_CODE)
        GROUP BY rpby.TAX_YEAR, rpby.STATE, rm.COUNTY, rm.MUNICIPALITY, rpby.PROPERTY_ID
    ) rp
    JOIN (
        SELECT rptt.STATE
        , rptt.TAX_YEAR
        , rptt.PROPERTY_ID
        , SUM(rptt.TOTAL_RENTAL_PAYMENTS) AS TOTAL_RENTAL_PAYMENTS
        FROM RAS.RAS_PROPERTY_TO_TENANT rptt
        GROUP BY rptt.STATE, rptt.TAX_YEAR, rptt.PROPERTY_ID
    ) tnt ON (tnt.TAX_YEAR = rp.TAX_YEAR AND tnt.PROPERTY_ID = rp.PROPERTY_ID)
;
