DROP VIEW RAS.SUMMARIZE_TENANTS_BY_COUNTY_VW;

CREATE VIEW RAS.SUMMARIZE_TENANTS_BY_COUNTY_VW
AS
    SELECT stbc.TAX_YEAR
    , stbc.STATE
    , stbc.COUNTY
    , SUM(stbc.HOUSEHOLD_COUNT) AS HOUSEHOLD_COUNT
    , SUM(stbc.TOTAL_RENTAL_PAYMENTS) AS TOTAL_RENTAL_PAYMENTS
    , SUM(stbc.RENTAL_INCOME_RECEIVED) AS RENTAL_INCOME_RECEIVED
    , SUM(stbc.RENTAL_INCOME_DIFFERENCE) AS RENTAL_INCOME_DIFFERENCE
    FROM RAS.SUMMARIZE_TENANTS_BY_CITY_VW stbc
    GROUP BY stbc.STATE, stbc.COUNTY, stbc.TAX_YEAR;
