DROP VIEW RAS.TENANT_PROFILE_VW;

CREATE VIEW RAS.TENANT_PROFILE_VW
AS
    SELECT rm.STATE
    , rm.COUNTY
    , rm.MUNICIPALITY
    , rptt.TAX_YEAR
    , rptt.TENANT_TAX_ID
    , rif.FIRST_NAME
    , rif.MIDDLE_NAME
    , rif.LAST_NAME
    , rif.GROSS_INCOME
    , rptt.PROPERTY_ID
    , rpd.PROPERTY_LOCATION
    , rpd.PROPERTY_CITY
    , rpd.PROPERTY_COUNTRY
    FROM RAS.RAS_PROPERTY_TO_TENANT rptt
    JOIN RAS.RAS_INDIVIDUAL_FILER rif ON (rif.TAX_YEAR = rptt.TAX_YEAR AND rif.TAXID = rptt.TENANT_TAX_ID)
    JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = rptt.PROPERTY_ID)
    JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpd.STATE and rm.CODE = rpd.MUNICIPALITY_CODE)

