DROP USER RAS CASCADE;

-- USER SQL
CREATE USER "RAS" IDENTIFIED BY "Lucinda11"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "RAS" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "RAS" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "RAS" WITH ADMIN OPTION;
ALTER USER "RAS" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "RAS" WITH ADMIN OPTION;
GRANT CREATE ROLE TO "RAS" WITH ADMIN OPTION;
GRANT CREATE LIBRARY TO "RAS" WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO "RAS" WITH ADMIN OPTION;
GRANT DEBUG CONNECT SESSION TO "RAS" WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO "RAS" WITH ADMIN OPTION;
GRANT CREATE DIMENSION TO "RAS" WITH ADMIN OPTION;
GRANT CREATE OPERATOR TO "RAS" WITH ADMIN OPTION;
GRANT CREATE INDEXTYPE TO "RAS" WITH ADMIN OPTION;
GRANT DEBUG ANY PROCEDURE TO "RAS" WITH ADMIN OPTION;
GRANT CREATE SESSION TO "RAS" WITH ADMIN OPTION;
GRANT CREATE RULE TO "RAS" WITH ADMIN OPTION;
GRANT CREATE EXTERNAL JOB TO "RAS" WITH ADMIN OPTION;
GRANT CREATE TABLE TO "RAS" WITH ADMIN OPTION;
GRANT CREATE TYPE TO "RAS" WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO "RAS" WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO "RAS" WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO "RAS" WITH ADMIN OPTION;
GRANT CREATE HIERARCHY TO "RAS" WITH ADMIN OPTION;
GRANT CREATE CUBE BUILD PROCESS TO "RAS" WITH ADMIN OPTION;
GRANT CREATE PROFILE TO "RAS" WITH ADMIN OPTION;
GRANT CREATE RULE SET TO "RAS" WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO "RAS" WITH ADMIN OPTION;
GRANT CREATE CUBE DIMENSION TO "RAS" WITH ADMIN OPTION;
GRANT CREATE CUBE TO "RAS" WITH ADMIN OPTION;
