SELECT rpd.STATE
--, rpd.PROPERTY_TYPE
, rpt.PROPERTY_DESCRIPTION
, count(*)
FROM RAS.RAS_PROPERTY_DESCRIPTION rpd
JOIN RAS.RAS_PROPERTY_TYPE rpt ON (rpt.PROPERTY_TYPE = rpd.PROPERTY_TYPE)
WHERE property_location != owner_address
AND (
rpt.PROPERTY_DESCRIPTION LIKE 'Residential%'
OR rpt.PROPERTY_DESCRIPTION LIKE 'Commercial%'
OR rpt.PROPERTY_DESCRIPTION LIKE 'Farm%'
OR rpt.PROPERTY_DESCRIPTION LIKE 'Apartment%'
OR rpt.PROPERTY_DESCRIPTION LIKE 'Industrial%'
)
GROUP BY rpd.STATE, rpt.PROPERTY_DESCRIPTION
