/*************************************************
*****************************************/
    INSERT INTO RAS.RAS_PROPERTY_DESCRIPTION
    (TAX_YEAR, PROPERTY_TYPE, IS_RENTAL_PROPERTY, PROPERTY_COUNTRY
    , PROPERTY_STATE, PROPERTY_COUNTY_CODE, PROPERTY_CITY, PROPERTY_LOCATION
    , OWNER_NAME, OWNER_CITY, OWNER_STATE, OWNER_ADDRESS, OWNER_ZIPCODE
    , OWNER_COUNTRY, CITY_STATE_ORIGINAL, PROPERTY_CLASS, NUMBER_OF_APARTMENTS
    , LANDLORD_TAXID, BLOCK, LOT, CENSUS_TRACT, CENSUS_BLOCK, YEAR_CONSTRUCTED
    , DEED_BOOK, DEED_NUMBER)
    SELECT '2014' TAX_YEAR
    , rpt.PROPERTY_TYPE
    , 'N' IS_RENTAL_PROPERTY
    , 'US' PROPERTY_COUNTRY
    , rstg.STATE PROPERTY_STATE
    , pij.COUNTY_DISTRICT PROPERTY_COUNTY_CODE
    , rstg.MUNICIPALITY PROPERTY_CITY
    , pij.PROPERTY_LOCATION
    , pij.OWNER_NAME
    , SUBSTR( pij.CITY_STATE, 1, (INSTR( pij.CITY_STATE, ',' )-1) ) OWNER_CITY
    , 'NJ' OWNER_STATE
    , pij.STREET_ADDRESS OWNER_ADDRESS
    , pij.ZIP_CODE OWNER_ZIP_CODE
    , NULL OWNER_COUNTRY
    , pij.CITY_STATE CITY_STATE_ORIGINAL
    , pij.PROPERTY_CLASS
    , 0 NUMBER_OF_APARTMENTS
    , '??????????' TAXID
    , pij.BLOCK
    , pij.LOT
    , pij.CENSUS_TRACT
    , pij.CENSUS_BLOCK
    , pij.YEAR_CONSTRUCTED
    , pij.DEED_BOOK
    , pij.DEED_PAGE
    FROM RAS_STG.PROPERTY_INFO_NJ pij
    JOIN RAS_STG.MUNICIPALITY_NJ rstg ON (rstg.code = pij.COUNTY_DISTRICT)
    JOIN RAS.RAS_PROPERTY_TYPE rpt ON (rpt.PROPERTY_CLASS =  pij.PROPERTY_CLASS)
    LEFT JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd 
    ON ( 
        rpd.owner_name = pij.OWNER_NAME 
        AND rpd.PROPERTY_LOCATION = pij.PROPERTY_LOCATION 
        AND rpd.block = pij.block 
        AND rpd.lot = pij.lot 
        )
    WHERE rpd.OWNER_NAME IS NULL;
--    AND pij.OWNER_NAME LIKE '%CHEVINE%';

INSERT INTO RAS.RAS_PROPERTY_BASE_YEAR
SELECT rpd.TAX_YEAR
, rpd.PROPERTY_ID
, rpd.PROPERTY_STATE
, rpd.PROPERTY_COUNTY_CODE
FROM RAS.RAS_PROPERTY_DESCRIPTION rpd
LEFT JOIN RAS.RAS_PROPERTY_BASE_YEAR rpby 
ON (rpby.TAX_YEAR = rpd.TAX_YEAR AND rpby.PROPERTY_ID = rpd.PROPERTY_ID)
WHERE rpby.PROPERTY_ID IS NULL;
