SELECT rpd.PROPERTY_LOCATION, rpd.OWNER_ADDRESS, rpd.OWNER_CITY, rpd.OWNER_NAME
FROM RAS.RAS_PROPERTY_BASE_YEAR rpby
JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpby.STATE AND rm.CODE = rpby.CODE)
JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.TAX_YEAR = rpby.TAX_YEAR AND rpd.PROPERTY_ID = rpby.PROPERTY_ID)
WHERE rm.STATE = 'NJ'
AND rm.COUNTY = 'UNION COUNTY'
AND rm.MUNICIPALITY LIKE 'PLAINFIELD%'
AND rpd.PROPERTY_LOCATION != rpd.OWNER_ADDRESS
--AND rpd.OWNER_NAME LIKE 'MILLER%CHEVINE%';
