INSERT INTO RAS.RAS_AUDIT(AUDIT_NAME, DESCRIPTION) VALUES('PROPERTY_ADDRESS_MISMATCH','The address for the property is not the same the address for the owner.');
INSERT INTO RAS.RAS_AUDIT(AUDIT_NAME, DESCRIPTION) VALUES('PROPERTY_HOUSEHOLD_COUNT','The number of head of households is very high for the property.');
INSERT INTO RAS.RAS_AUDIT(AUDIT_NAME, DESCRIPTION) VALUES('PROPERTY_NO_RENTAL_INCOME','A landlord has not reported any rental income for the property.');
INSERT INTO RAS.RAS_AUDIT(AUDIT_NAME, DESCRIPTION) VALUES('PROPERTY_LOW_RENTAL_INCOME','The amount of rental income reported for the property is too low.');
--INSERT INTO RAS.RAS_AUDIT(AUDIT_NAME, DESCRIPTION) VALUES('','');
--INSERT INTO RAS.RAS_AUDIT(AUDIT_NAME, DESCRIPTION) VALUES('','');
--INSERT INTO RAS.RAS_AUDIT(AUDIT_NAME, DESCRIPTION) VALUES('','');
--INSERT INTO RAS.RAS_AUDIT(AUDIT_NAME, DESCRIPTION) VALUES('','');
COMMIT;
