
  CREATE TABLE RAS_STG.MUNICIPALITY_NJ
   (    "CODE" CHAR(4) NOT NULL ENABLE, 
	"MUNICIPALITY" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"COUNTY" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_MUNICIPALITY_NJ" PRIMARY KEY ("CODE")
   );

  CREATE INDEX "MUNICIPALITY_NJ_IDX" ON RAS_STG.MUNICIPALITY_NJ ("MUNICIPALITY"); 
commit;
