
--
-- Table structure for table `us_states`
--

DROP TABLE US_STATES;
CREATE TABLE US_STATES (
	ID int NOT NULL,
	STATE_CODE char(2) NOT NULL,
	STATE_NAME varchar(50) NOT NULL
);

INSERT INTO US_STATES VALUES(1,'AL','Alabama');
INSERT INTO US_STATES VALUES(2,'AK','Alaska');
INSERT INTO US_STATES VALUES(3,'AZ','Arizona');
INSERT INTO US_STATES VALUES(4,'AR','Arkansas');
INSERT INTO US_STATES VALUES(5,'CA','California');
INSERT INTO US_STATES VALUES(6,'CO','Colorado');
INSERT INTO US_STATES VALUES(7,'CT','Connecticut');
INSERT INTO US_STATES VALUES(8,'DE','Delaware');
INSERT INTO US_STATES VALUES(9,'DC','District of Columbia');
INSERT INTO US_STATES VALUES(10,'FL','Florida');
INSERT INTO US_STATES VALUES(11,'GA','Georgia');
INSERT INTO US_STATES VALUES(12,'HI','Hawaii');
INSERT INTO US_STATES VALUES(13,'ID','Idaho');
INSERT INTO US_STATES VALUES(14,'IL','Illinois');
INSERT INTO US_STATES VALUES(15,'IN','Indiana');
INSERT INTO US_STATES VALUES(16,'IA','Iowa');
INSERT INTO US_STATES VALUES(17,'KS','Kansas');
INSERT INTO US_STATES VALUES(18,'KY','Kentucky');
INSERT INTO US_STATES VALUES(19,'LA','Louisiana');
INSERT INTO US_STATES VALUES(20,'ME','Maine');
INSERT INTO US_STATES VALUES(21,'MD','Maryland');
INSERT INTO US_STATES VALUES(22,'MA','Massachusetts');
INSERT INTO US_STATES VALUES(23,'MI','Michigan');
INSERT INTO US_STATES VALUES(24,'MN','Minnesota');
INSERT INTO US_STATES VALUES(25,'MS','Mississippi');
INSERT INTO US_STATES VALUES(26,'MO','Missouri');
INSERT INTO US_STATES VALUES(27,'MT','Montana');
INSERT INTO US_STATES VALUES(28,'NE','Nebraska');
INSERT INTO US_STATES VALUES(29,'NV','Nevada');
INSERT INTO US_STATES VALUES(30,'NH','New Hampshire');
INSERT INTO US_STATES VALUES(31,'NJ','New Jersey');
INSERT INTO US_STATES VALUES(32,'NM','New Mexico');
INSERT INTO US_STATES VALUES(33,'NY','New York');
INSERT INTO US_STATES VALUES(34,'NC','North Carolina');
INSERT INTO US_STATES VALUES(35,'ND','North Dakota');
INSERT INTO US_STATES VALUES(36,'OH','Ohio');
INSERT INTO US_STATES VALUES(37,'OK','Oklahoma');
INSERT INTO US_STATES VALUES(38,'OR','Oregon');
INSERT INTO US_STATES VALUES(39,'PA','Pennsylvania');
INSERT INTO US_STATES VALUES(40,'PR','Puerto Rico');
INSERT INTO US_STATES VALUES(41,'RI','Rhode Island');
INSERT INTO US_STATES VALUES(42,'SC','South Carolina');
INSERT INTO US_STATES VALUES(43,'SD','South Dakota');
INSERT INTO US_STATES VALUES(44,'TN','Tennessee');
INSERT INTO US_STATES VALUES(45,'TX','Texas');
INSERT INTO US_STATES VALUES(46,'UT','Utah');
INSERT INTO US_STATES VALUES(47,'VT','Vermont');
INSERT INTO US_STATES VALUES(48,'VA','Virginia');
INSERT INTO US_STATES VALUES(49,'WA','Washington');
INSERT INTO US_STATES VALUES(50,'WV','West Virginia');
INSERT INTO US_STATES VALUES(51,'WI','Wisconsin');
INSERT INTO US_STATES VALUES(52,'WY','Wyoming');

