create or replace PROCEDURE POPULATE_RAS_LANDLORD AS 
BEGIN
    INSERT INTO RAS.RAS_LANDLORD(
        TAX_YEAR, TAXID
        , FIRST_NAME, MIDDLE_NAME, LAST_NAME
        , GROSS_INCOME, IS_BUSINESS_TAXID
        , ADDRESS, CITY, STATE, ZIP_CODE
        , COUNTRY, OWNER_NAME_ORIGINAL
    )
    SELECT rs.*
    FROM (
        SELECT llord.TAX_YEAR AS TAX_YEAR
        , generate_number() AS TAXID
        , EXTRACT_NAME_PART(llord.OWNER_NAME, 'FIRST') AS FIRST_NAME
        , EXTRACT_NAME_PART(llord.OWNER_NAME, 'MIDDLE') AS MIDDLE_NAME
        , EXTRACT_NAME_PART(llord.OWNER_NAME, 'LAST') AS LAST_NAME
        , 0 AS GROSS_INCOME
        , 'N' AS IS_BUSINESS_TAXID
        , llord.OWNER_ADDRESS AS OWNER_ADDRESS
        , llord.OWNER_CITY AS OWNER_CITY
        , '' AS STATE
        , llord.OWNER_ZIPCODE AS OWNER_ZIPCODE
        , '' AS COUNTRY
        , llord.OWNER_NAME AS OWNER_NAME_ORIGINAL
        FROM (
            SELECT rpd.LOAD_TAX_YEAR AS TAX_YEAR
            , rpd.OWNER_NAME AS OWNER_NAME
            , rpd.OWNER_ADDRESS AS OWNER_ADDRESS
            , rpd.OWNER_CITY AS OWNER_CITY
            , rpd.OWNER_ZIPCODE AS OWNER_ZIPCODE
            , COUNT(*) AUDIT_COUNT
            FROM RAS.RAS_AUDIT_STATUS ras
            JOIN RAS.RAS_AUDIT_VIOLATION rav ON (rav.STATUS_ID = ras.STATUS_ID)
            JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.LOAD_TAX_YEAR = rav.TAX_YEAR AND rav.PROPERTY_ID = rpd.PROPERTY_ID)
            WHERE ras.AUDIT_STATUS IN ('CONFIRMED')
            GROUP BY rpd.LOAD_TAX_YEAR, rpd.OWNER_NAME, rpd.OWNER_ADDRESS, rpd.OWNER_CITY, rpd.OWNER_ZIPCODE
            ORDER BY COUNT(*) DESC
            FETCH NEXT 10000 ROWS ONLY
        ) llord
        LEFT JOIN RAS.RAS_LANDLORD rll ON (rll.TAX_YEAR = llord.TAX_YEAR AND rll.OWNER_NAME_ORIGINAL = llord.OWNER_NAME AND rll.ADDRESS = llord.OWNER_ADDRESS)
        WHERE rll.TAX_YEAR IS NULL
    ) rs
    LEFT JOIN RAS.RAS_LANDLORD rl ON (rl.TAXID = rs.TAXID)
    LEFT JOIN RAS.RAS_INDIVIDUAL_FILER rif ON (rif.TAX_YEAR = rs.TAX_YEAR AND rif.TAXID = rs.TAXID)
    WHERE rl.TAXID IS NULL
    AND rif.TAXID IS NULL;
END POPULATE_RAS_LANDLORD;
