create or replace PROCEDURE POPULATE_RAS_PROPERTY AS 
BEGIN
    INSERT INTO RAS.RAS_PROPERTY(
        TAX_YEAR, LANDLORD_TAX_ID, PROPERTY_ID, PERCENTAGE_OWNED
        , RENTAL_INCOME_RECEIVED, NUMBER_OF_PROPERTY_OWNERS
        , TOTAL_DEDUCTIONS, PROPERTY_TAXES
        , STATE, MUNICIPALITY_CODE
    )
    SELECT
    llprops.TAX_YEAR
    , llprops.LANDLORD_TAX_ID
    , llprops.PROPERTY_ID
    , 100 AS PERCENTAGE_OWNED
    , 0 AS RENTAL_INCOME_RECEIVED
    , 1 AS NUMBER_OF_PROPERTY_OWNERS
    , 0 AS TOTAL_DEDUCTIONS
    , 0 AS PROPERTY_TAXES
    , llprops.STATE
    , llprops.MUNICIPALITY_CODE
    FROM (
        SELECT rll.TAX_YEAR AS TAX_YEAR
        , rll.TAXID AS LANDLORD_TAX_ID
        , rpd.PROPERTY_ID AS PROPERTY_ID
        , rpd.STATE AS STATE
        , rpd.MUNICIPALITY_CODE AS MUNICIPALITY_CODE
        FROM RAS.RAS_LANDLORD rll
        JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.LOAD_TAX_YEAR = rll.TAX_YEAR
            AND rpd.OWNER_NAME = rll.OWNER_NAME_ORIGINAL
            AND rpd.OWNER_ADDRESS = rll.ADDRESS
            AND rpd.OWNER_CITY = rll.CITY
--            AND rpd.OWNER_NAME LIKE 'MILLER%CHEVINE%'
        )
        JOIN RAS.RAS_AUDIT_VIOLATION rav ON (rav.TAX_YEAR = rll.TAX_YEAR
            AND rav.PROPERTY_ID = rpd.PROPERTY_ID
        )
        GROUP BY rll.TAX_YEAR, rll.TAXID, rpd.PROPERTY_ID, rpd.STATE, rpd.MUNICIPALITY_CODE
    ) llprops
    LEFT OUTER JOIN RAS.RAS_PROPERTY rp ON (rp.TAX_YEAR = llprops.TAX_YEAR
        AND rp.LANDLORD_TAX_ID = llprops.LANDLORD_TAX_ID
        AND rp.PROPERTY_ID = llprops.PROPERTY_ID
    )
    WHERE rp.PROPERTY_ID IS NULL;
END POPULATE_RAS_PROPERTY;
