create or replace PROCEDURE RESET_RENTAL_INCOME_TENANT_PAYMENTS 
(
  P_TAX_YEAR IN VARCHAR2 DEFAULT '1900' 
) AS 
BEGIN
    -- Reset the rental income to zero
    UPDATE RAS.RAS_PROPERTY
    SET RENTAL_INCOME_RECEIVED = 0
    WHERE TAX_YEAR = P_TAX_YEAR;

    -- Reset the tenant payments to zero
    UPDATE RAS.RAS_PROPERTY_TO_TENANT
    SET TOTAL_RENTAL_PAYMENTS = 0
    WHERE TAX_YEAR = P_TAX_YEAR;
    
    UPDATE RAS.RAS_TENANT_PAYMENT_HISTORY
    SET TOTAL_PAYMENTS = 0
    WHERE TAX_YEAR = P_TAX_YEAR;
    
END RESET_RENTAL_INCOME_TENANT_PAYMENTS;
