MERGE
INTO RAS.RAS_INDIVIDUAL_FILER target 
USING (
    SELECT rpd.PROPERTY_ID
    , rpd.PROPERTY_LOCATION
    , rpd.OWNER_NAME AS OWNER_NAME
    , rpd.OWNER_ADDRESS AS OWNER_ADDRESS
    , rpd.CITY_STATE_ORIGINAL AS CITY_STATE_ORIGINAL
    , rpd.OWNER_ZIPCODE AS OWNER_ZIPCODE
    FROM RAS.RAS_PROPERTY_DESCRIPTION rpd
    LEFT JOIN RAS.RAS_INDIVIDUAL_FILER rif ON (rif.TAX_YEAR = rpd.LOAD_TAX_YEAR AND rif.PROPERTY_ID = rpd.PROPERTY_ID)
    WHERE EXTRACT_STREET_ADDRESS(rpd.PROPERTY_LOCATION) = EXTRACT_STREET_ADDRESS(rpd.OWNER_ADDRESS)
    --AND rpd.MUNICIPALITY_CODE = '2012'
    --AND (rpd.OWNER_NAME LIKE 'FY REALTY%'
    --OR rpd.OWNER_NAME LIKE 'HABIB%'
    --)
    --AND 1 = 2
    AND rif.PROPERTY_ID IS NULL
    FETCH NEXT 1000 ROWS ONLY
) source
ON (target.OWNER_NAME_ORIGINAL = source.OWNER_NAME AND target.OWNER_ADDRESS_ORIGINAL = source.OWNER_ADDRESS AND target.OWNER_CITY_ORIGINAL = source.CITY_STATE_ORIGINAL)
WHEN MATCHED THEN UPDATE
    SET target.PROPERTY_ID = source.PROPERTY_ID;
