DROP TRIGGER RAS_PROPERTY_DESCRIPTION_INS_AFTER_TRG;

CREATE OR REPLACE TRIGGER RAS_PROPERTY_DESCRIPTION_INS_AFTER_TRG 
AFTER INSERT ON RAS_PROPERTY_DESCRIPTION FOR EACH ROW
BEGIN
  INSERT INTO RAS.RAS_PROPERTY_BASE_YEAR(
    TAX_YEAR, PROPERTY_ID, STATE, CODE
    )
    VALUES(
        :new.LOAD_TAX_YEAR
        , :new.PROPERTY_ID
        , :new.STATE
        , :new.MUNICIPALITY_CODE
    );
END;
/
