CREATE OR REPLACE TRIGGER RAS_MUNICIPALITY_INS_BEFORE_TRG 
AFTER INSERT ON RAS.RAS_MUNICIPALITY FOR EACH ROW
BEGIN
    INSERT INTO RAS.RAS_STATE_COUNTY(
        STATE, COUNTY
    )
    VALUES(
        :new.STATE
        , :new.COUNTY
    );
END;
/
