-- USER SQL
ALTER USER "RAS_STG"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "RAS_STG" DEFAULT ROLE "PDB_DBA";

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE ROLE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE LIBRARY TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE OPERATOR TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE INDEXTYPE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE VIEW TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE TABLE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE TYPE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE PROFILE TO "RAS_STG" WITH ADMIN OPTION;
GRANT DROP USER TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO "RAS_STG" WITH ADMIN OPTION;

