-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2021-02-14 10:38:11 EST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



CREATE ROLE ras_stg_read_only NOT IDENTIFIED;

CREATE USER ras IDENTIFIED BY profile DEFAULT 
    ACCOUNT UNLOCK 
;

GRANT ADVISOR TO RAS 
;

GRANT CREATE LIBRARY, CREATE SESSION, DEBUG ANY PROCEDURE, DEBUG CONNECT SESSION, CREATE OPERATOR, CREATE TYPE, CREATE PROFILE, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, CREATE EXTERNAL JOB, CREATE INDEXTYPE, CREATE ROLE, CREATE CUBE, CREATE CUBE DIMENSION, CREATE DIMENSION, CREATE TRIGGER, CREATE SEQUENCE, CREATE VIEW, CREATE SYNONYM, CREATE MATERIALIZED VIEW, CREATE TABLE, CREATE JOB, CREATE RULE SET, CREATE hierarchy,
    CREATE CUBE BUILD PROCESS,
    CREATE RULE
TO ras WITH ADMIN OPTION;

CREATE USER ras_stg IDENTIFIED BY profile DEFAULT 
    ACCOUNT UNLOCK 
;

GRANT CREATE INDEXTYPE, CREATE LIBRARY, CREATE TYPE, CREATE SYNONYM, CREATE hierarchy,
    CREATE RULE,
    CREATE DIMENSION,
    CREATE PUBLIC SYNONYM,
    CREATE TABLE,
    UNLIMITED TABLESPACE,
    CREATE CUBE,
    CREATE OPERATOR,
    CREATE SEQUENCE,
    CREATE TRIGGER,
    CREATE PROCEDURE,
    CREATE JOB,
    CREATE ROLE,
    CREATE EXTERNAL JOB,
    CREATE RULE SET,
    CREATE VIEW
TO ras_stg WITH ADMIN OPTION;

CREATE OR REPLACE FUNCTION ras_stg.generate_number (
    number_width IN NUMBER DEFAULT 9
) RETURN NUMBER AS
    random_number NUMBER;
BEGIN
    SELECT
        trunc(dbms_random.value(10000000, 99999999))
    INTO random_number
    FROM
        dual;

    RETURN random_number;
END generate_number;
/

CREATE TABLE ras_stg.cam (
    a NUMBER
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT )
NO INMEMORY;

CREATE TABLE ras_stg.municipality_nj (
    code          CHAR(4 BYTE) NOT NULL,
    municipality  VARCHAR2(255 BYTE) NOT NULL,
    county        VARCHAR2(255 BYTE) NOT NULL
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT )
NO INMEMORY;

CREATE INDEX ras_stg.municipality_nj_idx ON
    ras_stg.municipality_nj (
        municipality
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

CREATE UNIQUE INDEX ras_stg.pk_municipality_nj ON
    ras_stg.municipality_nj (
        code
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

GRANT SELECT ON ras_stg.municipality_nj TO ras_stg_read_only;

ALTER TABLE ras_stg.municipality_nj
    ADD CONSTRAINT pk_municipality_nj PRIMARY KEY ( code )
        USING INDEX ras_stg.pk_municipality_nj;

CREATE TABLE ras_stg.property_class_nj (
    class_code   CHAR(3 BYTE) NOT NULL,
    description  VARCHAR2(200 BYTE)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT )
NO INMEMORY;

CREATE UNIQUE INDEX ras_stg.state_code_idx ON
    ras_stg.property_class_nj (
        class_code
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

GRANT SELECT ON ras_stg.property_class_nj TO ras_stg_read_only;

ALTER TABLE ras_stg.property_class_nj
    ADD CONSTRAINT state_code_idx PRIMARY KEY ( class_code )
        USING INDEX ras_stg.state_code_idx;

CREATE TABLE ras_stg.property_info_nj (
    county_district             CHAR(4 BYTE) NOT NULL,
    block                       CHAR(9 BYTE) NOT NULL,
    lot                         CHAR(9 BYTE) NOT NULL,
    qualifier                   CHAR(11 BYTE) NOT NULL,
    record_id                   CHAR(2 BYTE) NOT NULL,
    filler_1                    CHAR(2 BYTE) NOT NULL,
    transaction_date            CHAR(6 BYTE) NOT NULL,
    transaction_update_no       CHAR(4 BYTE),
    tax_account_number          CHAR(8 BYTE) NOT NULL,
    property_class              CHAR(3 BYTE) NOT NULL,
    property_location           CHAR(25 BYTE) NOT NULL,
    building_description        CHAR(15 BYTE) NOT NULL,
    land_description            CHAR(20 BYTE) NOT NULL,
    calculated_acreage          CHAR(9 BYTE) NOT NULL,
    addition_lots1              CHAR(20 BYTE) NOT NULL,
    addition_lots2              CHAR(20 BYTE) NOT NULL,
    zoning                      CHAR(4 BYTE) NOT NULL,
    tax_map_page_number         CHAR(4 BYTE) NOT NULL,
    owner_name                  CHAR(35 BYTE) NOT NULL,
    street_address              CHAR(25 BYTE) NOT NULL,
    city_state                  CHAR(25 BYTE) NOT NULL,
    zip_code                    CHAR(9 BYTE) NOT NULL,
    number_of_owners            CHAR(4 BYTE) NOT NULL,
    deduction_amount            CHAR(6 BYTE) NOT NULL,
    filler2                     CHAR(1 BYTE) NOT NULL,
    bank_code                   CHAR(5 BYTE) NOT NULL,
    mortgage_account_number     CHAR(10 BYTE) NOT NULL,
    deed_book                   CHAR(5 BYTE) NOT NULL,
    deed_page                   CHAR(5 BYTE) NOT NULL,
    sales_price_code            CHAR(1 BYTE) NOT NULL,
    deed_date                   CHAR(6 BYTE),
    sale_price                  CHAR(9 BYTE) NOT NULL,
    sale_assessment             CHAR(9 BYTE) NOT NULL,
    sale_sr1a_un_code           CHAR(2 BYTE) NOT NULL,
    social_security_no          CHAR(9 BYTE) NOT NULL,
    school_tax_overage          CHAR(9 BYTE) NOT NULL,
    no_of_dwellings             CHAR(2 BYTE) NOT NULL,
    no_of_commercial_dw         CHAR(2 BYTE) NOT NULL,
    multiple_occupancy          CHAR(1 BYTE) NOT NULL,
    percent_owned_code          CHAR(1 BYTE) NOT NULL,
    rebate_code                 CHAR(2 BYTE) NOT NULL,
    delinquent_code             CHAR(1 BYTE) NOT NULL,
    epl_own                     CHAR(2 BYTE) NOT NULL,
    epl_use                     CHAR(2 BYTE) NOT NULL,
    epl_desc                    CHAR(3 BYTE) NOT NULL,
    initial_date                CHAR(6 BYTE) NOT NULL,
    further_date                CHAR(6 BYTE) NOT NULL,
    statute_number              CHAR(12 BYTE) NOT NULL,
    facility_name               CHAR(20 BYTE) NOT NULL,
    building_class_code         CHAR(5 BYTE) NOT NULL,
    year_constructed            CHAR(4 BYTE) NOT NULL,
    assessment_code             CHAR(1 BYTE) NOT NULL,
    land_value                  CHAR(9 BYTE) NOT NULL,
    improvement_value           CHAR(9 BYTE) NOT NULL,
    net_value                   CHAR(9 BYTE) NOT NULL,
    special_tax_code1           CHAR(3 BYTE) NOT NULL,
    special_tax_code2           CHAR(3 BYTE) NOT NULL,
    special_tax_code3           CHAR(3 BYTE) NOT NULL,
    special_tax_code4           CHAR(3 BYTE) NOT NULL,
    exemption_code1             CHAR(1 BYTE) NOT NULL,
    exemption_amt1              CHAR(8 BYTE) NOT NULL,
    exemption_code2             CHAR(1 BYTE) NOT NULL,
    exemption_amt2              CHAR(8 BYTE) NOT NULL,
    exemption_code3             CHAR(1 BYTE) NOT NULL,
    exemption_amt3              CHAR(8 BYTE) NOT NULL,
    exemption_code4             CHAR(1 BYTE) NOT NULL,
    exemption_amt4              CHAR(8 BYTE) NOT NULL,
    senior_citizens_cnt         CHAR(4 BYTE),
    veterans_cnt                CHAR(4 BYTE),
    widows_cnt                  CHAR(4 BYTE),
    surv_spouse_cnt             CHAR(3 BYTE),
    disabled_cnt                CHAR(3 BYTE),
    user_field1                 CHAR(4 BYTE),
    user_field2                 CHAR(4 BYTE),
    old_property_id             CHAR(29 BYTE),
    census_tract                CHAR(5 BYTE),
    census_block                CHAR(4 BYTE),
    property_use_code           CHAR(3 BYTE),
    property_flags              CHAR(10 BYTE),
    rebate_response_flg         CHAR(1 BYTE),
    rebate_base_year            CHAR(4 BYTE),
    rebate_base_year_tax        CHAR(9 BYTE),
    rebate_base_year_net_val    CHAR(9 BYTE),
    filler3                     CHAR(5 BYTE),
    last_year_tax               CHAR(9 BYTE),
    current_year_tax            CHAR(9 BYTE),
    non_municipal_half1         CHAR(9 BYTE),
    non_municipal_half2         CHAR(9 BYTE),
    municipal_half1             CHAR(9 BYTE),
    municipal_half2             CHAR(9 BYTE),
    non_municipal_half3         CHAR(9 BYTE),
    municipal_half3             CHAR(9 BYTE),
    bill_status_flag            CHAR(1 BYTE),
    estimated_qtr3_tax          CHAR(9 BYTE) NOT NULL,
    prior_year_net_value        CHAR(9 BYTE),
    statement_of_state_aid_amt  CHAR(9 BYTE)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT )
NO INMEMORY;

CREATE TABLE ras_stg.us_cities (
    id         NUMBER(*, 0) NOT NULL,
    id_state   NUMBER(*, 0) NOT NULL,
    city       VARCHAR2(50 BYTE) NOT NULL,
    county     VARCHAR2(50 BYTE),
    latitude   NUMBER NOT NULL,
    longitude  NUMBER NOT NULL
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT )
NO INMEMORY;

CREATE TABLE ras_stg.us_states (
    id          NUMBER(*, 0) NOT NULL,
    state_code  CHAR(2 BYTE) NOT NULL,
    state_name  VARCHAR2(50 BYTE) NOT NULL
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT )
NO INMEMORY;

ALTER TABLE ras_stg.property_info_nj
    ADD CONSTRAINT fk_county_district_nj FOREIGN KEY ( county_district )
        REFERENCES ras_stg.municipality_nj ( code )
    NOT DEFERRABLE;

ALTER TABLE ras_stg.property_info_nj
    ADD CONSTRAINT fk_state_property_class_nj FOREIGN KEY ( property_class )
        REFERENCES ras_stg.property_class_nj ( class_code )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             3
-- ALTER TABLE                              4
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          1
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              1
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              2
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
