-- USER SQL
CREATE USER "RAS_STG" IDENTIFIED BY "Rasadmin11"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "RAS_STG" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "RAS_STG" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "RAS_STG" WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE ROLE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE LIBRARY TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO "RAS_STG" WITH ADMIN OPTION;
GRANT DEBUG CONNECT SESSION TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE DIMENSION TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE OPERATOR TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE INDEXTYPE TO "RAS_STG" WITH ADMIN OPTION;
GRANT DEBUG ANY PROCEDURE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE VIEW TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE SESSION TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE RULE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE TABLE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE TYPE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO "RAS_STG" WITH ADMIN OPTION;
GRANT DEBUG CONNECT ANY TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE PROFILE TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE RULE SET TO "RAS_STG" WITH ADMIN OPTION;
GRANT CREATE CUBE TO "RAS_STG" WITH ADMIN OPTION;

