CREATE OR REPLACE FUNCTION EXTRACT_ADDRESS_PART 
(
  FULL_ADDRESS IN VARCHAR2 
, ADDRESS_PART IN VARCHAR2 DEFAULT 'STREET' 
) RETURN VARCHAR2 AS 
EXTRACTED_STREET_PART VARCHAR2(255);
BEGIN
-- The function assumes that the name of the street/road/avenue
-- is preceded by a number.
    IF ADDRESS_PART = 'STREET' THEN
        SELECT REGEXP_REPLACE( TRIM(FULL_ADDRESS), '([0-9]+[-]?[0-9]*)([ ]+)', '')
        INTO EXTRACTED_STREET_PART
        FROM DUAL;
    ELSE 
        IF ADDRESS_PART = 'NUMBER' THEN
            SELECT substr(TRIM(FULL_ADDRESS), 1, INSTR(TRIM(FULL_ADDRESS), ' '))
            INTO EXTRACTED_STREET_PART
            FROM DUAL;
        ELSE
            SELECT FULL_ADDRESS INTO EXTRACTED_STREET_PART FROM DUAL;
        END IF;
    END IF;
  RETURN EXTRACTED_STREET_PART;
END EXTRACT_ADDRESS_PART;
