SELECT rm.STATE AS STATE
, rm.COUNTY AS COUNTY
, rm.MUNICIPALITY AS CITY
, COUNT(*) AS PROPERTY_COUNT
FROM RAS.RAS_MUNICIPALITY rm
JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.STATE = rm.STATE AND rpd.MUNICIPALITY_CODE = rm.CODE)
JOIN RAS.RAS_PROPERTY_TYPE rpt ON (rpt.PROPERTY_CLASS = rpd.PROPERTY_CLASS)
--WHERE rpt.PROPERTY_CLASS IN ('2', '3A', '3B', '4A', '4B', '4C')
GROUP BY rm.STATE, rm.COUNTY, rm.MUNICIPALITY;
