SELECT muni."STATE"
, muni.COUNTY
, muni.MUNICIPALITY
, pinfo.PROPERTY_LOCATION
, pc.DESCRIPTION PROPERTY_DESCRIPTION
, pinfo.LAND_DESCRIPTION
, pinfo.OWNER_NAME
, pinfo.STREET_ADDRESS OWNER_STREET_ADDRESS
, pinfo.CITY_STATE OWNER_CITY_STATE
, pinfo.ZIP_CODE OWNER_ZIP_CODE
FROM RAS.MUNICIPALITY_NJ muni
LEFT JOIN RAS.PROPERTY_INFO_NJ pinfo 
ON (pinfo."STATE" = muni."STATE" AND pinfo.COUNTY_DISTRICT = muni.CODE)
JOIN RAS.PROPERTY_CLASS_NJ pc 
ON (pc."STATE" = pinfo."STATE" AND pc.CLASS_CODE = pinfo.PROPERTY_CLASS)
--WHERE pinfo.OWNER_NAME LIKE 'BELIN,%'
