SELECT rm.STATE AS STATE
, rm.COUNTY AS COUNTY
, rm.MUNICIPALITY
, rpd.PROPERTY_LOCATION
, rpd.OWNER_NAME
, rpd.OWNER_ADDRESS
, rpd.OWNER_CITY
, rpd.OWNER_STATE
, rpd.OWNER_ZIPCODE
, rpd.OWNER_COUNTRY
, rpd.IS_RENTAL_PROPERTY
FROM RAS_MUNICIPALITY rm
JOIN RAS_PROPERTY_DESCRIPTION rpd ON (rpd.STATE = rpd.state AND rpd.MUNICIPALITY_CODE = rm.CODE)
