SELECT rav.TAX_YEAR AS TAX_YEAR
, ra.AUDIT_NAME AS AUDIT_NAME
, rm.STATE AS STATE
, rm.COUNTY AS COUNTY
, rm.MUNICIPALITY AS CITY
, COUNT(*) AS AUDIT_CHECK_COUNT
, ra.DESCRIPTION AS DESCRIPTION
FROM RAS.RAS_AUDIT_VIOLATION rav
JOIN RAS.RAS_AUDIT ra ON (ra.AUDIT_ID = rav.AUDIT_ID)
JOIN RAS.RAS_PROPERTY_DESCRIPTION rpd ON (rpd.PROPERTY_ID = rav.PROPERTY_ID)
JOIN RAS.RAS_MUNICIPALITY rm ON (rm.STATE = rpd.STATE AND rm.CODE = rpd.MUNICIPALITY_CODE)
GROUP BY rav.TAX_YEAR, rm.STATE, rm.COUNTY, rm.MUNICIPALITY, ra.AUDIT_NAME, ra.DESCRIPTION
