CREATE ROLE RAS_STG_READ_ONLY;

GRANT SELECT ON RAS_STG.MUNICIPALITY_NJ TO RAS_STG_READ_ONLY;
GRANT SELECT ON RAS_STG.PROPERTY_CLASS_NJ TO RAS_STG_READ_ONLY;
GRANT SELECT ON RAS_STG.PROPERTY_INFO_NJ TO RAS_STG_READ_ONLY;

GRANT RAS_STG_READ_ONLY TO RAS;

ALTER USER RAS DEFAULT ROLE RAS_STG_READ_ONLY;
